apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-{{ .Values.databaseVolumeClaim.name }}
spec:
#  storageClassName: manual
  accessModes:
    {{ .Values.databaseVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.databaseVolumeClaim.storage }}
