apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.app.podPreset.name }}
spec:
  selector:
    matchLabels:
      app: {{ include "todolist.fullname" . }}-{{ .Values.app.deployment.template.labels.app }}
  env:
    - name: DB_HOST
      value: todolist-db-svc
    - name: DB_PORT
      value: "5432"
    - name: DB_PASSWORD
      value: "password"