apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.app.deployment.name }}
  labels:
    app: {{ include "todolist.fullname" . }}-{{ .Values.app.deployment.labels.app }}
spec:
  replicas: {{ .Values.app.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "todolist.fullname" . }}-{{ .Values.app.deployment.template.labels.app }}
  template:
    metadata:
      labels:
        app: {{ include "todolist.fullname" . }}-{{ .Values.app.deployment.template.labels.app }}
        role: {{ .Values.app.deployment.template.labels.role }}
    spec:
      containers:
        - name: {{ include "todolist.fullname" . }}-{{ .Values.app.deployment.template.containers.name }}
          image: {{ .Values.app.deployment.template.containers.image }}
          ports:
            - containerPort: {{ .Values.app.deployment.template.containers.ports.containerPort }}
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 10
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 20
