apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.app.service.name }}
spec:
  selector:
    app: {{ include "todolist.fullname" . }}-{{ .Values.app.deployment.template.labels.app }}
  ports:
    - protocol: {{ .Values.app.service.protocol }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  type: {{ .Values.app.service.type }}