apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.db.service.name }}
spec:
  selector:
    app: {{ include "todolist.fullname" . }}-{{ .Values.db.deployment.template.labels.app }}
  ports:
    - protocol: {{ .Values.db.service.protocol }}
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}