apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.ingress.name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "todolist.fullname" . }}-{{ .Values.app.service.name }}
              servicePort: {{ .Values.app.service.port }}