apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todolist.fullname" . }}-{{ .Values.databaseVolumeClaim.name }}
spec:
  accessModes:
    {{ .Values.databaseVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.databaseVolumeClaim.storage }}