apiVersion: v1
kind: Pod
metadata:
  name: todolist-app-pod
  labels:
    app: todolist-app
    role: backend
spec:
  containers:
    - name: todolist-app-container
      image: nsnikhil/todolist:v0.12
      readinessProbe:
        exec:
          command: ["/bin/grpc_health_probe", "-addr=:8080"]
        initialDelaySeconds: 10
      livenessProbe:
        exec:
          command: ["/bin/grpc_health_probe", "-addr=:8080"]
        initialDelaySeconds: 20