name: Go

on:
  push:
    branches: 
      - master

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: make deps

    - name: Test
      env:
        POSTGRES_HOST: 127.0.0.1
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
      run: |
        sudo apt-get install -y wget ca-certificates
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
        sudo service postgresql restart
        sleep 5
        make copy-config
        make build
        make migrate
        make test

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13 
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Docker file
      run: docker build -t nsnikhil10/todolist:v0.12 -f deployment/docker/Dockerfile .

    - name: Push to Docker hub
      env:
        DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER_NAME --password-stdin
        docker push nsnikhil/todolist:v0.12
    
