name: Go

on:
  push:
    branches: 
      - master

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: make deps

    - name: Test
      run: make test

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13 
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: make deps

    - name: Build Docker file
      run: docker build -t nsnikhil10/todolist:v0.1 -f deployment/docker/Dockerfile .

    - name: Push to Docker hub
      env:
        DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER_NAME --password-stdin
        docker push nsnikhil10/todolist:v0.1
    
